version: '3.8'
services:
  dev-db:
    image: postgres:15
    ports:
     - 5434:5432
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - codewind
networks:
 codewind: